apiVersion: apps/v1
kind: Deployment
metadata: 
  name: web-dep
spec:
  replicas: 1
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: web
  template: 
    metadata:
      labels:
        app: web
    spec: 
      containers:
        - image: ajaypb1122/web-py:v2
          name: web-container
          ports:
            - name: web
              containerPort:  8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command: ['curl', 'localhost:8080']
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
  - name: web
    port:  8080
    targetPort: 8080